spring:
  application:
    name: security-security
  #settings of postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/danik_db
    driverClassName: org.postgresql.Driver
    username: danik
    password: danikmay
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855